baseURL = "https://mjstealey.github.io/irods-provider-galera/"
languageCode = "en-us"
title = "iRODS - MariaDB Galera cluster"
theme = "docdock"
publishDir = "../docs"

[params]
#editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
#unfoldedMenus = ["poc"] # set menu identifiers which should be displayed unfolded
themeVariant = "blue" # choose theme variant "green", "gold" , "blue" (default)

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repository"
identifier = "repo"
url = "https://github.com/mjstealey/irods-provider-galera/"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> iRODS Documentation"
identifier = "irodsdoc"
url = "https://irods.org/documentation/"
weight = 2

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> MariaDB Documentation"
identifier = "mariadoc"
url = "https://mariadb.com/kb/en/mariadb/documentation/"
weight = 3
